/*
 * Copyright (c) 2010, NanChang BangTeng Inc
 * All Rights Reserved.
 *
 * You may use the Software for free for non-commercial use
 * under the License Restrictions.
 *
 * You may modify the source code(if being provieded) or interface
 * of the Software under the License Restrictions.
 *
 * You may use the Software for commercial use after purchasing the
 * commercial license.Moreover, according to the license you purchased
 * you may get specified term, manner and content of technical
 * support from NanChang BangTeng Inc
 *
 * See COPYING file for detail.
 */
#ifndef LANG_H_INCLUDE_SDLFKJ
#define LANG_H_INCLUDE_SDLFKJ
#include "KLang.h"
#define LANG_COPY_RIGHT_STR "(c) 2010 NanChang BangTeng Inc"
//#define VER_STRING     klang["VER_STRING"] 
#define LANG_CHARSET klang["LANG_CHARSET"] 
#define LANG_READ_CONFIG_FILE   klang["LANG_READ_CONFIG_FILE"] 
#define LANG_SUCCESS   klang["LANG_SUCCESS"] 
#define LANG_ERROR klang["LANG_ERROR"] 
#define LANG_USER klang["LANG_USER"] 
#define LANG_PASS klang["LANG_PASS"] 
#define LANG_SUBMIT klang["LANG_SUBMIT"] 
#define LANG_MANAGE   klang["LANG_MANAGE"] 
#define LANG_CONNECT_PER_IP klang["LANG_CONNECT_PER_IP"] 
#define LANG_CONNECTION   klang["LANG_CONNECTION"] 
#define LANG_USERS klang["LANG_USERS"] 
#define LANG_LOGIN_USERS klang["LANG_LOGIN_USERS"] 
#define LANG_HOME klang["LANG_HOME"] 
#define LANG_LOGOUT   klang["LANG_LOGOUT"] 
#define LANG_CHANGE_PASSWD klang["LANG_CHANGE_PASSWD"] 
#define LANG_ACCESS klang["LANG_ACCESS"] 
#define LANG_INFO klang["LANG_INFO"] 
#define LANG_CONFIG klang["LANG_CONFIG"] 
#define LANG_WORKING_THREAD   klang["LANG_WORKING_THREAD"] 
#define LANG_FREE_THREAD klang["LANG_FREE_THREAD"] 
#define LANG_OBJ_CACHE_INFO klang["LANG_OBJ_CACHE_INFO"] 
#define LANG_TOTAL_OBJ_COUNT   klang["LANG_TOTAL_OBJ_COUNT"] 
#define LANG_TOTAL_MEM_CACHE   klang["LANG_TOTAL_MEM_CACHE"] 
#define LANG_TOTAL_DISK_CACHE   klang["LANG_TOTAL_DISK_CACHE"] 
#define LANG_UPTIME klang["LANG_UPTIME"] 
#define LANG_TOTAL_RUNING klang["LANG_TOTAL_RUNING"] 
#define LANG_THREAD_INFO klang["LANG_THREAD_INFO"] 
#define LANG_DAY klang["LANG_DAY"] 
#define LANG_HOUR klang["LANG_HOUR"] 
#define LANG_MIN klang["LANG_MIN"] 
#define LANG_SECOND   klang["LANG_SECOND"] 
#define LANG_SERVICE   klang["LANG_SERVICE"] 
#define LANG_CACHE klang["LANG_CACHE"] 
#define LANG_LOG klang["LANG_LOG"] 
#define LANG_OTHER_CONFIG klang["LANG_OTHER_CONFIG"] 
#define LANG_RS_LIMIT   klang["LANG_RS_LIMIT"] 
#define LANG_PORT klang["LANG_PORT"] 
#define LANG_TIME_OUT   klang["LANG_TIME_OUT"] 
#define LANG_OPERATOR   klang["LANG_OPERATOR"] 
#define LANG_URL klang["LANG_URL"] 
#define LANG_FLAG klang["LANG_FLAG"] 
#define LANG_DELETE klang["LANG_DELETE"] 
#define LANG_IGNORE_CASE klang["LANG_IGNORE_CASE"] 
#define LANG_IP   klang["LANG_IP"] 
#define LANG_MIN_REFRESH_TIME   klang["LANG_MIN_REFRESH_TIME"] 
#define LANG_IF_USE_DISK_CACHE   klang["LANG_IF_USE_DISK_CACHE"] 
#define LANG_ON klang["LANG_ON"] 
#define LANG_OFF klang["LANG_OFF"] 
#define LANG_LOG_ROTATE_TIME   klang["LANG_LOG_ROTATE_TIME"] 
#define LANG_TOTAL_MAX_THREAD   klang["LANG_TOTAL_MAX_THREAD"] 
#define LANG_TOTAL_THREAD_EACH_IP klang["LANG_TOTAL_THREAD_EACH_IP"] 
#define LANG_MAX_PER_IP_DEAL klang["LANG_MAX_PER_IP_DEAL"] 
#define LANG_DEAL_QUEUE   klang["LANG_DEAL_QUEUE"] 
#define LANG_DEAL_CLOSE   klang["LANG_DEAL_CLOSE"] 
#define LANG_MIN_LIMIT_SPEED_SIZE   klang["LANG_MIN_LIMIT_SPEED_SIZE"] 
#define LANG_LIMIT_SPEED   klang["LANG_LIMIT_SPEED"] 
#define LANG_ANTI_FATBOY klang["LANG_ANTI_FATBOY"] 
#define LANG_MAX_REQUEST klang["LANG_MAX_REQUEST"] 
#define LANG_TOTAL_SECONDS klang["LANG_TOTAL_SECONDS"] 
#define LANG_ANTI_FATBOY_URL   klang["LANG_ANTI_FATBOY_URL"] 
#define LANG_INSERT_X_FORWARDED_FOR klang["LANG_INSERT_X_FORWARDED_FOR"] 
#define LANG_CANNOT_WRITE_WARING klang["LANG_CANNOT_WRITE_WARING"] 
#define LANG_INDEX klang["LANG_INDEX"] 
#define LANG_SRC_IP klang["LANG_SRC_IP"] 
#define LANG_ACTION   klang["LANG_ACTION"] 
#define LANG_DENY klang["LANG_DENY"] 
#define LANG_ALLOW klang["LANG_ALLOW"] 
#define LANG_DEFAULT_TABLE_NAME   klang["LANG_DEFAULT_TABLE_NAME"] 
#define LANG_TABLE klang["LANG_TABLE"] 
#define LANG_REFS   klang["LANG_REFS"] 
#define LANG_HIT_COUNT   klang["LANG_HIT_COUNT"] 
#define LANG_INSERT klang["LANG_INSERT"] 
#define LANG_ADD klang["LANG_ADD"] 
#define LANG_EMPTY klang["LANG_EMPTY"] 
#define LANG_NAME klang["LANG_NAME"] 
#define LANG_ADD_TABLE_SUCCESS_MSG klang["LANG_ADD_TABLE_SUCCESS_MSG"] 
#define LANG_ADD_TABLE_FAILED_MSG klang["LANG_ADD_TABLE_FAILED_MSG"] 
#define LANG_INPUT_TABLE_MSG   klang["LANG_INPUT_TABLE_MSG"] 
#define LANG_DEFAULT_INPUT_TABLE_NAME   klang["LANG_DEFAULT_INPUT_TABLE_NAME"] 
#define LANG_TABLE_NAME_LENGTH_ERROR klang["LANG_TABLE_NAME_LENGTH_ERROR"] 
#define LANG_TABLE_NAME_IS_USED   klang["LANG_TABLE_NAME_IS_USED"] 
#define LANG_CANNOT_DELETE_DEFAULT_TABLE   klang["LANG_CANNOT_DELETE_DEFAULT_TABLE"] 
#define LANG_CANNOT_RENAME_DEFAULT_TABLE   klang["LANG_CANNOT_RENAME_DEFAULT_TABLE"] 
#define LANG_RENAME_TABLE_INPUT_MSG klang["LANG_RENAME_TABLE_INPUT_MSG"] 
#define LANG_RENAME   klang["LANG_RENAME"] 
#define LANG_TABLE_NAME_ERR klang["LANG_TABLE_NAME_ERR"] 
#define LANG_TABLE_REFS_ERR klang["LANG_TABLE_REFS_ERR"] 
#define LANG_METH klang["LANG_METH"] 
#define LANG_HTTP_HEAD   klang["LANG_HTTP_HEAD"] 
#define LANG_HTTP_VALUE   klang["LANG_HTTP_VALUE"] 
#define LANG_STATE klang["LANG_STATE"] 
#define LANG_CONNECT_TIME klang["LANG_CONNECT_TIME"] 
#define LANG_HEAD klang["LANG_HEAD"] 
#define LANG_VALUE klang["LANG_VALUE"] 
#define LANG_ATTRIB klang["LANG_ATTRIB"] 
#define LANG_REVERS klang["LANG_REVERS"] 
#define LANG_ACCESS_FIRST klang["LANG_ACCESS_FIRST"] 
#define LANG_CONFIRM_DELETE klang["LANG_CONFIRM_DELETE"] 
#define LANG_CONFIRM_EMPTY klang["LANG_CONFIRM_EMPTY"] 
#define LANG_CONFIRM_CHANGE_FIRST klang["LANG_CONFIRM_CHANGE_FIRST"] 
#define LANG_CHANGE_FIRST_ACCESS   klang["LANG_CHANGE_FIRST_ACCESS"] 
#define LANG_MANAGE_ADMIN klang["LANG_MANAGE_ADMIN"] 
#define LANG_ADMIN_USER   klang["LANG_ADMIN_USER"] 
#define LANG_ADMIN_PASS   klang["LANG_ADMIN_PASS"] 
#define LANG_ADMIN_IPS   klang["LANG_ADMIN_IPS"] 
#define LANG_EDIT   klang["LANG_EDIT"] 
#define LANG_ACSERVER   klang["LANG_ACSERVER"] 
#define LANG_VHS		klang["LANG_VHS"]
#define LANG_WRITE_BACK   klang["LANG_WRITE_BACK"] 
#define LANG_MSG klang["LANG_MSG"] 
#define LANG_CONNECT_COUNT klang["LANG_CONNECT_COUNT"] 
#define LANG_MAX_CONNECT_PER_IP   klang["LANG_MAX_CONNECT_PER_IP"] 
#define LANG_RUN_USER klang["LANG_RUN_USER"] 
#define LANG_SN_ERROR   klang["LANG_SN_ERROR"] 
#define LANG_FATBOY   klang["LANG_FATBOY"] 
#define LANG_TOTAL_FATBOY klang["LANG_TOTAL_FATBOY"] 
#define LANG_FILTER_CONTENT_KEYS   klang["LANG_FILTER_CONTENT_KEYS"] 
#define LANG_BIND_ADDR  klang["LANG_BIND_ADDR"] 
#define LANG_NO_CACHE   klang["LANG_NO_CACHE"] 
#define LANG_OTHER_FLAG   klang["LANG_OTHER_FLAG"] 
#define LANG_NO_FILTER   klang["LANG_NO_FILTER"] 
#define LANG_FONT_SIZE   klang["LANG_FONT_SIZE"] 
#define LANG_MAX_CACHE_SIZE klang["LANG_MAX_CACHE_SIZE"] 
#define LANG_INSERT_VIA   klang["LANG_INSERT_VIA"] 
#define LANG_TABLE_NOT_EMPTY   klang["LANG_TABLE_NOT_EMPTY"] 
#define LANG_REWRITE_REFERER klang["LANG_REWRITE_REFERER"] 
#define LANG_NO_CHECK_CC klang["LANG_NO_CHECK_CC"] 
#define LANG_USE_PATH_INFO klang["LANG_USE_PATH_INFO"] 
#endif 

