name: kangle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: sudo apt -y install g++ liburing-dev libjemalloc-dev libz-dev libpcre3-dev libbrotli-dev libssl-dev cmake libsqlite3-dev
    - name: submodule
      run: git submodule init && git submodule update
    - name: cmake
      run: mkdir build && cd build && cmake .. -DLINUX_IOURING=ON -DENABLE_BROTLI=1
    - name: make
      run: cd build && make
    - name: build test
      run: sudo snap install go --classic && cd test && ./build.sh
    - name: test
      run: cd test && ./test.sh

