name: kangle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: apt -y install g++  liburing-dev libjemalloc-dev libz-dev libpcre3-dev libbrotli-dev libssl-dev cmake libsqlite3-dev
    - name: submodule
      run: git submodule init && git submodule update
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
